---
layout: custom
title: "Welcome to Our Special Campaign"
subtitle: "Join us in our effort to make a difference"
header_image: "/assets/images/custom-header.jpg"
featured_sections:
  - title: "Feature 1"
    description: "Description of feature 1."
    image: "/assets/images/feature1.jpg"
    link: "/feature-1/"
  - title: "Feature 2"
    description: "Description of feature 2."
    link: "/feature-2/"
testimonials:
  - quote: "This is an amazing project!"
    author: "Jane Doe"
  - quote: "Truly a remarkable experience."
    author: "John Smith"
---

Your main content goes here. This will be displayed in the intro section.
