- title: "Web Development"
  description: "Creating modern, responsive, and effective websites. Full-stack development services to build responsive and efficient websites."
  link: "/2023-12-07-FeatureWebDevelopment"
  icon: fa-code

- title: "Graphic Design"
  description: "Creative design solutions for digital and print media."
  icon: fa-paint-brush

- title: "Digital Marketing"
  description: "Strategies that elevate your brand's online presence. Comprehensive digital marketing strategies to enhance your online presence."
  link: "/2023-12-07-FeatureDigitalMarketing"
  icon: fa-bullhorn

- title: "Consulting"
  description: "Expert consulting services to help you optimize your business operations."
  icon: fa-handshake

- title: "UI/UX Design"
  description: "Designing intuitive and user-friendly interfaces."
  link: "/2023-12-07-FeatureUI-UXDesign"
