theme_color: "#0055aa"
feature_toggles:
  enable_blog: true
  enable_e_commerce: false
  show_testimonials: true
api_keys:
  google_maps: "YOUR_GOOGLE_MAPS_API_KEY"
  mailchimp: "YOUR_MAILCHIMP_API_KEY"
contact_info:
  email: support@vcwtech.com
  phone: "+1(555)555-5555"
analytics:
  google_analytics: "G-QH33T8MYJZ"
social_media:
  facebook: "https://www.facebook.com/yourpage"
  twitter: "https://twitter.com/yourprofile"
  instagram: "https://www.instagram.com/yourprofile"

# Add additional configuration parameters as needed
